import { agencyInfo } from "./agencies";
import type { ComplaintRecord } from "./types";

export function toMarkdown(record: ComplaintRecord): string {
  const agency = agencyInfo(record.agency);
  const lines = [
    `# AduanAI Complaint Report — ${record.reference}`,
    "",
    `- **Filed:** ${new Date(record.createdAt).toLocaleString("en-MY")}`,
    `- **Complaint type:** ${record.complaintType}`,
    `- **Location:** ${record.location}`,
    `- **Urgency:** ${record.urgency.toUpperCase()}`,
    `- **Routed agency:** ${agency.code} — ${agency.name}`,
    `- **Submission channel:** ${agency.channel}`,
    `- **Status:** ${record.status}`,
    `- **Triage source:** ${record.source === "live" ? "live AI model" : "mock fallback engine"}`,
    "",
    "## Summary",
    record.summary,
    "",
    "## Recommended steps",
    ...record.steps.map((step, index) => `${index + 1}. ${step}`),
    "",
    "## Next action",
    record.nextAction,
    "",
    "## Original complaint",
    "> " + record.input.replace(/\n+/g, "\n> "),
    "",
    "---",
    "_Generated by AduanAI — Intelligent Public Complaint & Service Request Triage for Malaysia._",
  ];
  return lines.join("\n");
}

export function referenceFor(date: Date, seed: number): string {
  const stamp = `${date.getFullYear()}${String(date.getMonth() + 1).padStart(2, "0")}${String(date.getDate()).padStart(2, "0")}`;
  return `ADU-${stamp}-${String(seed).padStart(3, "0")}`;
}
